name: Docker Image CI

on:
  push:
    branches: [ "tufts-geoserver-dummy" ]
  pull_request:
    branches: [ "tufts-geoserver-dummy" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - 
      name: checkout branch
      uses: actions/checkout@v2
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{secrets.REGISTRY_URL}}/tufts-geoserver:$(date +%s)'
    - 
      name: Login to private registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./server/
        file: ./server/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: '${{ secrets.REGISTRY_URL }}/my-project/server:latest'
        cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/my-project/server:buildcache'
        cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/my-project/server:buildcache,mode=max'
